# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: GitHub Pages
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # schedule:
  #   # Melbourne new year converted to UTC
  #   - cron: 1 13 31 12 *
jobs:
  pages:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{github.workflow}}-${{github.ref}}
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Set-up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            /tmp/hugo_cache
            resources/_gen/images
          key: ${{runner.os}}-hugomod-${{hashFiles('**/go.sum')}}
          restore-keys: ${{runner.os}}-hugomod-
      # - name: Install LaTeX
      #   run: sudo apt install texlive texlive-latex-extra fonts-firacode
      - name: Build
        run: |
          # printf "\ngoogleAnalytics: $GOOGLE_ANALYTICS" >> hugo.yml
          make website
        env:
          GOOGLE_ANALYTICS: ${{secrets.GOOGLE_ANALYTICS}}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./public