# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: ag22website
before:
  hooks:
    - make build
archives:
  - name_template: "{{.ProjectName}}_{{.Version}}"
    files:
      - public
    format_overrides:
      - format: zip