baseURL = "http://applegamer22.github.io/"
languageCode = "en-au"
defaultContentLanguage = "en"
title = "Omri Bornstein"
theme = "gokarna"
enableRobotsTXT = true
pygmentsStyle = "monokai"
[params]
favicon = "favicon-32x32.png"
avatarURL = "favicon.png"
showPostsOnHomePage = "recent"
socialIcons = [
    {name = "github", url = "https://github.com/AppleGamer22"},
    {name = "linkedin", url = "https://www.linkedin.com/in/omri-bornstein/"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/7148921/applegamer22"},
    {name = "twitter", url = "https://twitter.com/AppleGamer22"},
]
customHeadHTML = """
<!-- KaTeX -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>
"""
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
[menu]
  [[menu.main]]
    identifier = "home"
    url = "/"
    name = "Home"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/AppleGamer22"
    weight = 5
	pre = "<span data-feather='github'></span>"
  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/omri-bornstein/"
    weight = 6
    pre = "<span data-feather='linkedin'></span>"
  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7