# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
module:
  imports:
    - path: github.com/jpanther/congo/v2
baseURL: https://applegamer22.github.io
languageCode: en-au
defaultContentLanguage: en
title: Omri Bornstein
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  colorScheme: fruit
  enableCodeCopy: true
  enableSearch: true
  mainSections: ["posts"]
  homepage:
    layout: profile
    showRecent: true
  article:
    showBreadcrumbs: true
    showTableOfContents: true
    showTaxonomies: true
    showWordCount: true
    showEdit: true
    editAppendPath: false
    editURL: https://github.com/AppleGamer22/applegamer22.github.io
    sharingLinks:
      - linkedin
      - reddit
      - twitter
      - email
  list:
    showTableOfContents: true
  footer:
    showAppearanceSwitcher: true
markup:
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false
languages:
  en:
    languageName: English
    # dateFormat: 02-01-2006
    author:
      name: Omri Bornstein
      image: "/author.png"
      headline: Computer Science Student, Gopher, TeXnician
      bio: Computer Science Student, Gopher, TeXnician
      links:
        - linkedin: https://www.linkedin.com/in/omri-bornstein/
        - email: mailto:omribor@gmail.com
        - github: https://github.com/AppleGamer22
        - gitlab: https://gitlab.com/AppleGamer22
        - stack-overflow: https://stackoverflow.com/users/7148921/
        # - orcid: https://orcid.org/0000-0001-8645-6321
        - dev: https://dev.to/applegamer22
        - hashnode: https://applegamer22.hashnode.dev
        - medium: https://medium.com/@AppleGamer22
        - twitter: https://twitter.com/AppleGamer22
    menu:
      main:
        - name: Blog
          pageRef: posts
          weight: 1
        - name: Projects
          pageRef: projects
          weight: 2
        - name: Tags
          pageRef: tags
          weight: 3
