# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
module:
  imports:
    - path: github.com/jpanther/congo/v2
baseURL: https://applegamer22.github.io
timeZone: Australia/Melbourne
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
defaultContentLanguage: en
title: Omri Bornstein
paginate: 15
summaryLength: 0
outputs:
  home:
    - HTML
    - RSS
    - JSON
privacy:
  disqus:
    disable: true
  youtube:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
params:
  colorScheme: fruit
  defaultAppearance: dark
  enableCodeCopy: true
  enableSearch: true
  mainSections:
    - posts
    - interviews
  homepage:
    layout: profile
    showRecent: true
  header:
    layout: custom
  article:
    showBreadcrumbs: true
    showTableOfContents: true
    showTaxonomies: true
    showWordCount: true
    showEdit: true
    showDateUpdated: true
    editURL: https://github.com/AppleGamer22/applegamer22.github.io/tree/master/content
    sharingLinks:
      - email
      - github
      - gitlab
      - linkedin
      - reddit
      - twitter
      - facebook
      - pinterest
  list:
    showTableOfContents: true
    showBreadcrumbs: true
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false
languages:
  en:
    languageName: English
    languageCode: en
    isoCode: en
    rtl: false
    weight: 1
    title: Omri Bornstein
    description: Omri Bornstein's personal website
    author:
      name: Omri Bornstein
      image: "/author.png"
      headline: Computer Science Student, Gopher, TeXnician
      bio: Computer Science Student, Gopher, TeXnician
      links:
        - email: mailto:omribor@gmail.com
        - linkedin: https://www.linkedin.com/in/omri-bornstein/
        - github: https://github.com/AppleGamer22
        - gitlab: https://gitlab.com/AppleGamer22
        - stack-overflow: https://stackoverflow.com/users/7148921/
        - keybase: https://keybase.io/applegamer22
        - orcid: https://orcid.org/0000-0001-8645-6321
        - dev: https://dev.to/applegamer22
        - hashnode: https://applegamer22.hashnode.dev
        - medium: https://medium.com/@AppleGamer22
        - codepen: https://codepen.io/AppleGamer22
        - ctftime: https://ctftime.org/user/106208
        - tryhackme: https://tryhackme.com/p/AppleGamer22
        - hackthebox: https://app.hackthebox.com/profile/529539
        - leetcode: https://leetcode.com/AppleGamer22/
    menu:
      main:
        - name: About
          pageRef: about
          weight: 1
        - name: Posts
          pageRef: posts
          weight: 2
        - name: Events
          pageRef: events
          weight: 3
        - name: Projects
          pageRef: projects
          weight: 4
        - name: CV
          url: /cv.pdf
          weight: 5
        - name: Tags
          pageRef: tags
          weight: 6
