# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
module:
  imports:
    - path: github.com/jpanther/congo/v2
baseURL: https://applegamer22.github.io
timeZone: Australia/Melbourne
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
defaultContentLanguage: en
title: Omri Bornstein
paginate: 15
summaryLength: 0
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  colorScheme: fruit
  # defaultAppearance: dark
  enableCodeCopy: true
  enableSearch: true
  mainSections:
    - talks
    - posts
    - projects
  homepage:
    layout: profile
    showRecent: true
    # recentLimit: 10
  header:
    logo: logo.png
    layout: custom
  footer:
    showAppearanceSwitcher: true
  article:
    showTableOfContents: true
    showBreadcrumbs: true
    showTaxonomies: true
    showWordCount: true
    showEdit: true
    showDateUpdated: true
    editURL: https://github.com/AppleGamer22/applegamer22.github.io/tree/master/content
    sharingLinks:
      - email
      - github
      - gitlab
      - linkedin
      - mastodon
      - reddit
      - twitter
      - facebook
      - pinterest
  list:
    showTableOfContents: true
    showBreadcrumbs: true
    showTaxonomies: true
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false
languages:
  en:
    languageName: English
    languageCode: en-au
    isoCode: en-AU
    rtl: false
    dateFormat: "2006-01-02"
    weight: 1
    title: Omri Bornstein
    description: Omri Bornstein's personal website
    author:
      name: Omri Bornstein
      image: "/author.png"
      headline: Computer Science Student, Gopher, TeXnician
      bio: Computer Science Student, Gopher, TeXnician
      links:
        - email: mailto:omribor@gmail.com
        - linkedin: https://www.linkedin.com/in/omri-bornstein/
        - github: https://github.com/AppleGamer22
        # - gitlab: https://gitlab.com/AppleGamer22
        # - gitea: https://gitea.com/AppleGamer22
        - stack-overflow: https://stackoverflow.com/users/7148921/
        - keybase: https://keybase.io/applegamer22
        # - orcid: https://orcid.org/0000-0001-8645-6321
        - dev: https://dev.to/applegamer22
        # - hashnode: https://hashnode.com/@AppleGamer22
        # - medium: https://medium.com/@AppleGamer22
        # - codepen: https://codepen.io/AppleGamer22
        - ctftime: https://ctftime.org/user/106208
        - tryhackme: https://tryhackme.com/p/AppleGamer22
        # - hackthebox: https://app.hackthebox.com/profile/529539
        # - leetcode: https://leetcode.com/AppleGamer22/
        # - hackerrank: https://www.hackerrank.com/applegamer22
        - mastodon: https://mastodon.au/@AppleGamer22
    menu:
      main:
        - name: About
          pageRef: about
          weight: 1
        - name: Posts
          pageRef: posts
          weight: 2
        - name: Talks
          pageRef: talks
          weight: 3
        - name: Projects
          pageRef: projects
          weight: 4
        - name: CV
          # url: /cv.pdf
          pageRef: cv
          params:
            target: _blank
          weight: 5
        - name: Tags
          pageRef: tags
          weight: 6
      footer:
        - name: Privacy
          pageRef: privacy
        - name: Licence
          url: https://www.gnu.org/licenses/gpl-3.0.en.html
          params:
            target: _blank
        - name: RSS
          url: /index.xml
          params:
            target: _blank
