# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Dependency Review
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
permissions:
  contents: read
jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: low
