# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: GitHub Pages
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # At 00:01 on day-of-month 1 in January
    # https://crontab.guru/#1_0_1_1_*
    - cron: 1 0 1 1 *
      timezone: Australia/Melbourne
jobs:
  pages:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{github.workflow}}-${{github.ref}}
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Set-up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # hugo-version: latest
          hugo-version: "0.148.1"
          extended: true
      - name: Cache
        uses: actions/cache@v5
        with:
          path: /home/runner/.cache/hugo_cache
          key: ${{runner.os}}-hugomod-${{hashFiles('**/go.sum')}}
          restore-keys: ${{runner.os}}-hugomod-
      - name: Build
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          GOOGLE_ANALYTICS: ${{secrets.GOOGLE_ANALYTICS}}
        run: |
          printf "\ngoogleAnalytics: $GOOGLE_ANALYTICS" >> hugo.yml
          make website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./public