name: GitHub Pages
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set-up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{runner.os}}-hugomod-${{hashFiles('**/go.sum')}}
          restore-keys: |
            ${{runner.os}}-hugomod-
      # - name: Install LaTeX
      #   run: sudo apt install texlive texlive-latex-extra
      - name: Build
        run: |
          echo "config:\n  googleAnalytics: ${{secrets.GOOGLE_ANALYTICS}}" >> config.yml
          make website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./public